# aws-values.yaml
global:
    awsCredentials:
        region: us-east-1

awsCredentials:
    aws_access_key_id: aws_access_key_id
    aws_secret_access_key: aws_secret_access_key
    region: us-east-1