gatewayCreds:
  namespace: opscruise
  environment:
    DOCKER_SERVER: "index.docker"
    DOCKER_USERNAME: "username"
    DOCKER_PASSWORD: "password"
    DOCKER_EMAIL: "email"
    OPSCRUISE_ENDPOINT: "192.168.43.188:9092"
    KEYCLOAK_ENABLED: "false"
    KEYCLOAK_URL: "https://auth.opscruise.io:8443"
    KEYCLOAK_CLIENT_ID: "kafka-client"
    KEYCLOAK_CLIENT_SECRET: "<KEYCLOAK_CLIENT_SECRET>"
    KEYCLOAK_REALM: "<KEYCLOAK_REALM>"
    OPSCRUISE_ACCOUNT_ID: "anything"

dockerCredentials:
    registry: https://index.docker.io/v1/
    username: username
    password: password
