apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    k8s-app: {{ .Values.k8sapp }}
  name:  {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
        opscruisePerimeter: {{ .Values.opscruisePerimeter }}
        opscruiseGroup: {{ .Values.opscruiseGroup }}
        opscruiseProduct: {{ .Values.opscruiseProduct }}
        opscruiseStream: {{ .Values.opscruiseStream }}
    spec:
      containers:
        -
          args:
            - "--profiling"
            - "--housekeeping_interval=1s"
            - "--enable_load_reader=true"
            - "--disable_metrics=udp,tcp"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          name: {{ .Values.name }}
          ports:
            -
              containerPort: {{ .Values.ports.containerPort }}
              name: {{ .Values.ports.name }}
              protocol: {{ .Values.ports.protocol }}
          volumeMounts:
            -
              mountPath: {{ .Values.volumeMounts.rootfsmountPath }}
              name: {{ .Values.volumeMounts.rootfsname }}
              readOnly: {{ .Values.volumeMounts.rootfsreadOnly }}
            -
              mountPath: {{ .Values.volumeMounts.varrunmountPath }}
              name: {{ .Values.volumeMounts.varname }}
              readOnly: {{ .Values.volumeMounts.varrunreadOnly }}
            -
              mountPath: {{ .Values.volumeMounts.sysmountPath }}
              name: {{ .Values.volumeMounts.sysname }}
              readOnly: {{ .Values.volumeMounts.sysreadOnly }}
            -
              mountPath: {{ .Values.volumeMounts.dockermountPath }}
              name: {{ .Values.volumeMounts.dockername }}
              readOnly: {{ .Values.volumeMounts.dockerreadOnly }}
            -
              mountPath: {{ .Values.volumeMounts.diskmountPath }}
              name: {{ .Values.volumeMounts.diskname }}
              readOnly: {{ .Values.volumeMounts.diskreadOnly }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      tolerations:
        -
          effect: {{ .Values.tolerations.effect }}
          key: {{ .Values.tolerations.key }}
      volumes:
        -
          hostPath:
            path: {{ .Values.volumes.rootfspath }}
          name: {{ .Values.volumes.rootfsname }}
        -
          hostPath:
            path: {{ .Values.volumes.runpath }}
          name: {{ .Values.volumes.runname }}
        -
          hostPath:
            path: {{ .Values.volumes.syspath }}
          name: {{ .Values.volumes.sysname }}
        -
          hostPath:
            path: {{ .Values.volumes.dockerpath }}
          name: {{ .Values.volumes.dockername }}
        -
          hostPath:
            path: {{ .Values.volumes.diskpath }}
          name: {{ .Values.volumes.diskname }}
