# Default values for helm-chart-prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.17.1
  pullPolicy: Always

args:
  configFile: '--config.file=/etc/prometheus/prometheus.yml'

ports:
  containerPort: 9090

resources:
  limits:
    memory: 600Mi
  requests:
    cpu: 200m
    memory: 300Mi

volumeMounts:
 mountPath: /etc/prometheus

hostNetwork: true
hostPID: true

volumes:
 configMap: prometheus-configmap

restartPolicy: Always