# Default values for promGW.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: promgw-deployment
# namespace: opscruise
app: promgw
opscruisePerimeter: opscruise
opscruiseGroup: gateways
opscruiseProduct: promGW
opscruiseStream: opscruise

replicaCount: 1

image:
  repository: opscruiseindia/oc-promgw
  tag: <VERSION>
  pullPolicy: Always
  containerPort: 8080

env:
  lvalue: "warning"

envFrom:
  secretRefname: oc-gw-creds

ports:
 containerPort: 8080

volumeMounts:
  name: promgw-certs-volume
  mountPath: /var/opscruise/certs

imagePullSecrets:
  name: oc-docker-creds

restartPolicy: Always

secret:
  secretName: oc-gw-certs

service:
  app: promgw
  name: promgw-service
  # namespace: opscruise
  opscruisePerimeter: opscruise
  opscruiseGroup: gateways
  opscruiseProduct: promGW
  opscruiseStream: opscruise
  protocol: TCP
  port: 8585
  targetPort: 8080

resources:
 limits:
  cpu: 500m
  memory: 300Mi
 requests:
  cpu: 200m
  memory: 50Mi


