apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus
        opscruisePerimeter: opscruise
        opscruiseGroup: exporters
        opscruiseProduct: prometheus
        opscruiseStream: opscruise

    spec:
      containers:
      - name: prometheus
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
          - "{{ .Values.args.configFile }}"
        ports:
          - name: web
            containerPort: {{ .Values.ports.containerPort }}
        volumeMounts:
          - name: config-volume
            mountPath: "{{ .Values.volumeMounts.mountPath }}"

      volumes:
      - name: config-volume
        configMap:
          name: "{{ .Values.volumes.configMap }}"

      restartPolicy: "{{ .Values.restartPolicy }}"
