apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: "{{ .Release.Namespace }}"
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: 'oc-kubernetes-pods'
        scheme: http
        kubernetes_sd_configs:
        - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_opscruisePerimeter]
          regex: opscruise
          action: keep

    remote_write:
      - url: "http://promgw-service.opscruise.svc.cluster.local:8585/ingest"
        queue_config:
          max_samples_per_send: 120000
          capacity: 360000

