apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: awsgw
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: awsgw

  template:
    metadata:
      labels:
        app: awsgw
        opscruisePerimeter: opscruise
        opscruiseGroup: gateways
        opscruiseProduct: awsGW
        opscruiseStream: opscruise
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOGLEVEL
              value: "{{ .Values.env.lvalue }}"
            - name: AWS_REGION
              value: {{ .Values.global.awsCredentials.region }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFrom.secretRefname1 }}
            - secretRef:
                name: {{ .Values.envFrom.secretRefname2 }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
          resources:
{{ toYaml .Values.resources | indent 12 }}

      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}

      volumes:
        - name: {{ .Values.volumeMounts.name }}
          secret:
            secretName: {{ .Values.secret.secretName }}

      restartPolicy: {{ .Values.restartPolicy }}

