apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: collectors
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: 'oc-kubernetes-pods'
        scheme: http
        kubernetes_sd_configs:
        - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+):(?:\d+);(\d+)
          replacement: ${1}:${2}
          target_label: __address__

    remote_write:
      - url: "http://promgw-service.opscruise.svc.cluster.local:8585/ingest"
        queue_config:
          max_samples_per_send: 120000

