apiVersion: apps/v1
kind: Deployment
metadata:
  name: promgw-deployment
  namespace: opscruise
  labels:
    app: promgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promgw

  template:
    metadata:
      labels:
        app: promgw
        opscruisePerimeter: opscruise
        opscruiseGroup: gateways
        opscruiseProduct: promGW
        opscruiseStream: opscruise

    spec:
      containers:
      - name: promgw-container
        image: opscruiseindia/oc-promgw:promgw1.1.0
        imagePullPolicy: Always
        env:
          - name: LOGLEVEL
            value: "warning"
        envFrom:
          - secretRef:
              name: oc-gw-creds

        ports:
        - containerPort: 8080

        volumeMounts:
        - name: promgw-certs-volume
          mountPath: /var/opscruise/certs

        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 50Mi

      imagePullSecrets:
        - name: oc-docker-creds

      volumes:
      - name: promgw-certs-volume
        secret:
          secretName: oc-gw-certs

      restartPolicy: Always
