# Default values for Kubernetes State Metrics Cluster Role.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: kube-state-metrics
k8sapp: kube-state-metrics
# namespace: collectors
opscruisePerimeter: opscruise
opscruiseGroup: exporters
opscruiseProduct: KSM
opscruiseStream: opscruise

replicaCount: 1

image:
  repository: quay.io/coreos/kube-state-metrics
  tag: v1.6.0

ports:
  name1: http-metrics
  containerPort1: 8080
  name2: telemetry
  containerPort2: 8081

readinessProbe:
  path: /healthz
  port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 5

serviceAccount:
 name: kube-state-metrics
#  namespace: collectors

ClusterRoleBinding:
  name: kube-state-metrics

