# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: opscruiseindia/oc-awsgw
  tag: <VERSION>
  pullPolicy: IfNotPresent

env:
  lvalue: "warning"
  awsregionvalue: us-east-1

envFrom:
  secretRefname1: oc-gw-creds
  secretRefname2: oc-aws-credential

volumeMounts:
  name: awsgw-certs-volume
  mountPath: /var/opscruise/certs

imagePullSecrets:
  name: oc-docker-creds

restartPolicy: Always

secret:
  secretName: oc-gw-certs

resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 200m
    memory: 50Mi

awsCredentials:
  aws_access_key_id: aws_access_key_id
  aws_secret_access_key: aws_secret_access_key
  region: us-east-1