apiVersion: v1
kind: Secret
metadata:
  name: oc-aws-credential
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID:  {{ .Values.awsCredentials.aws_access_key_id |b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.aws_secret_access_key |b64enc }}