apiVersion: v1
kind: Secret
metadata:
  name: oc-gw-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.gatewayCreds.environment }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}