- name: copy prometheus deployment yaml for kubernetes
  copy:
    src: ./prometheus-deployment.yaml
    dest: /opt/opscruise/prometheus/

- name: copy prometheus configmap yaml for kubernetes
  copy:
    src: ./prometheus-configmap.yml
    dest: /opt/opscruise/prometheus/

- name: copy prometheus clusterrole for kubernetes
  copy:
    src: ./clusterRole.yaml
    dest: /opt/opscruise/prometheus/

#    - name: replace with cadvisor hosts
#      replace:
#        path: /opt/opscruise/prometheus/prometheus-configmap.yml
#        regexp: 'PROMETHEUS_CADVISOR_TARGETS'
#        replace: "{{ prometheus_cadvisor_targets }}"

- name: running prometheus-server as a Deployment
  shell: |
    export KUBECONFIG=/opt/opscruise/admin.conf && kubectl create -f /opt/opscruise/prometheus/clusterRole.yaml
    kubectl create -f /opt/opscruise/prometheus/prometheus-configmap.yml
    kubectl create -f /opt/opscruise/prometheus/prometheus-deployment.yaml
