# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: opscruiseindia/oc-k8sgw
  tag: <VERSION>
  pullPolicy: Always

env:
  lvalue: "warning"

envFrom:
  secretRef: oc-gw-creds

volumeMounts:
  name: k8s-certs-volume
  mountPath: /var/opscruise/certs

imagePullSecrets:
  name: oc-docker-creds

restartPolicy: Always

secret:
  secretName: oc-gw-certs

resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 200m
    memory: 50Mi

subjects:
 name: default
#  namespace: opscruise

